# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786d5ed6af8a1b0080edc34393843913581664f755eca106dde258b1663f66ba306553d3af662eb2a0206721b726109e3591cdc566f48a154ea724331a4d928b

test:
  secret_key_base: 1102675d6241cec706b88d6b9f457ebe80a457045ebe45891ba9c1b9e6e465a84cfa0c7d56c28378bb6a29715d11b3f7276c870ed9ea729aac0c8c1d1efd4327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
